// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1UVCxFbIGzgaZQcNALLSzJp1cceMcfkg',
    appId: '1:241157259282:web:25003c3ec34e435fe858cb',
    messagingSenderId: '241157259282',
    projectId: 'dating-app-360',
    authDomain: 'dating-app-360.firebaseapp.com',
    storageBucket: 'dating-app-360.firebasestorage.app',
    measurementId: 'G-V79EE03FW1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEnkU_3T5BFJkiA5DutzAws8wLYerPaYw',
    appId: '1:241157259282:android:fdb6cea7f46aa44ce858cb',
    messagingSenderId: '241157259282',
    projectId: 'dating-app-360',
    storageBucket: 'dating-app-360.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9rLtesKCFFmgrQJAc7qP47KlnsqomfjU',
    appId: '1:241157259282:ios:719c073b9c55f413e858cb',
    messagingSenderId: '241157259282',
    projectId: 'dating-app-360',
    storageBucket: 'dating-app-360.firebasestorage.app',
    iosClientId: '241157259282-vblqc3irutrvo010h05fk08ocdli13cd.apps.googleusercontent.com',
    iosBundleId: 'com.example.datingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9rLtesKCFFmgrQJAc7qP47KlnsqomfjU',
    appId: '1:241157259282:ios:719c073b9c55f413e858cb',
    messagingSenderId: '241157259282',
    projectId: 'dating-app-360',
    storageBucket: 'dating-app-360.firebasestorage.app',
    iosClientId: '241157259282-vblqc3irutrvo010h05fk08ocdli13cd.apps.googleusercontent.com',
    iosBundleId: 'com.example.datingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1UVCxFbIGzgaZQcNALLSzJp1cceMcfkg',
    appId: '1:241157259282:web:c40e863ddf4c68ade858cb',
    messagingSenderId: '241157259282',
    projectId: 'dating-app-360',
    authDomain: 'dating-app-360.firebaseapp.com',
    storageBucket: 'dating-app-360.firebasestorage.app',
    measurementId: 'G-4FLF9BGH65',
  );
}
